FROM openjdk:8-jdk-alpine
MAINTAINER by liujianxin
VOLUME ["/tmp"]
ARG JAR_FILE
COPY ${JAR_FILE} provider1.jar
ENTRYPOINT [ "sh", "-c", "java -Xms256m -Xmx256m -XX:+UseSerialGC -Dexportip=121.36.142.5 -Dport=8001 -Ddatasource=datasource.yaml -Dproviderid=provider1 -Djava.security.egd=file:/dev/./urandom -jar /provider1.jar" ]
