server:
  port: 8002
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.seefly.microserviceapi.entites
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: microservicecloud-dept
eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002:7002/eureka,http://eureka7003.com:7003/eureka/
      defaultZone: http://192.168.10.64:8090/eureka
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true
info:
  app.name: seefly-microservicecloud
  company.name: www.seefly.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$