server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.10.62 #eureka服务端的实例名称
  client:
    register-with-eureka: false #自己不注册到eureka，因为自己是个eurekaServer
    fetch-registry: false #不从注册中心检索服务实例，因为不需要
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.85 # 自我保护中，计算最少需要收到心跳数的百分比阈值
    enable-self-preservation: true #开启自我保护
    renewal-threshold-update-interval-ms: 900000 # 更新触发自我保护阈值参数的时间间隔，默认15分钟
