server:
  port: 7001
eureka:
  instance:
    hostname: 192.168.10.62 #eureka服务端的实例名称
    lease-renewal-interval-in-seconds: 30 # 多少秒续约一次
    lease-expiration-duration-in-seconds: 90 # 租约，意思就是一次续约保证90秒内不会被剔除。
  client:
    register-with-eureka: false #自己不注册到eureka，因为自己是个eurekaServer
    fetch-registry: false #不从注册中心检索服务实例，因为不需要
    service-url:
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://192.168.10.64:7001/eureka
  server:
    renewal-percent-threshold: 0.85 # 自我保护中，计算最少需要收到心跳数的百分比阈值
    enable-self-preservation: true #开启自我保护
    renewal-threshold-update-interval-ms: 900000 # 更新触发自我保护阈值参数的时间间隔，默认15分钟
    response-cache-auto-expiration-in-seconds: 180 #双层缓存中，读写缓存的失效时间
    use-read-only-response-cache: true # 是否启用只读缓存，生产生产环境建议开启。开发环境关掉，只使用读写缓存，能够快速感知服务下线
    response-cache-update-interval-ms: 30000 # 读写缓存和只读缓存的同步周期，越小就能越快感知服务下线
    eviction-interval-timer-in-ms: 60000 # 多久扫秒一次超时未心跳的实例进行剔除
    retention-time-in-m-s-in-delta-queue: 180000 # 最近变更队列中元素的生存时间
    delta-retention-timer-interval-in-ms: 30000 # 多久清理一次最近变更队列
