server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.seefly.microserviceapi.entites
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.252.178:3306/cloudDB01?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: shang2010
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002:7002/eureka,http://eureka7003.com:7003/eureka/
      defaultZone: http://192.168.10.64:8090/eureka # eurekaServer地址，单机版
  instance:
    instance-id: microservicecloud-dept8001 #实例ID
    prefer-ip-address: true #访问路径可以显示IP地址
info:
  app.name: seefly-microservicecloud
  company.name: www.seefly.top
  build.artifactId: $project.artifactId$ #maven对这resources文件夹进行扫描，替换 $...$之间的变量
  build.version: $project.version$ #需要配置resource插件