server:
  port: 8003
spring:
  application:
    name: provider-sentinel
  cloud:
    sentinel:
      transport:
        port: 8719
        #dashboard: 121.36.142.5:8849
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: 121.36.142.5:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
feign:
  sentinel:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://121.36.142.5:7001/eureka
  instance:
    instance-id: provider-sentinel-local
    prefer-ip-address: true #是
    ip-address: 192.168.10.62
info:
  app.name: seefly-microservicecloud
  company.name: www.seefly.top
  build.artifactId: @project.artifactId@ #maven\u5BF9\u8FD9resources\u6587\u4EF6\u5939\u8FDB\u884C\u626B\u63CF\uFF0C\u66FF\u6362 $...$\u4E4B\u95F4\u7684\u53D8\u91CF
  build.version: @project.version@ #\u9700\u8981\u914D\u7F6Eresource\u63D2\u4EF6
management:
  endpoints:
    web:
      exposure:
        include: "*"
