server:
  port: 8008
spring:
  application:
    name: microservicecloud-seata


eureka:
  client:
    service-url:
      defaultZone: http://121.36.142.5:7001/eureka
  instance:
    instance-id: micro-provider-seata
    prefer-ip-address: true
    ip-address: 192.168.10.62

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: tx_group_test
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: false
  #excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  config:
    type: file
  registry:
    type: eureka
    load-balance: RandomLoadBalance
    load-balance-virtual-nodes: 10
    eureka:
      weight: 1
      service-url: http://121.36.142.5:7001/eureka
  service:
    vgroup-mapping:
      tx_group_test: seata-server
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  client:
    rm:
      async-commit-buffer-limit: 10000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      saga-json-parser: fastjson
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
      default-global-transaction-timeout: 60000
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  log:
    exception-rate: 100



info:
  app.name: seefly-microservicecloud
  company.name: www.seefly.top #???
  build.artifactId: @project.artifactId@
  build.version: @project.version@
