server:
  port: 6001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        # localhost:6001/guoji ---> http://news.baidu.com/guoji
        - id: guoji
          uri: http://news.baidu.com/
          predicates:
            - Path=/guoji
        # \u5BF9\u4E8E/sleep \u8BF7\u6C42\u90FD\u8F6C\u53D1\u5230\u8FD9\u4E2A\u670D\u52A1\u4E0A
        # see https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gateway-request-predicates-factories
        - id: provider-a
          uri: lb://microservicecloud-dept
          predicates:
            - Path=/sleep/**
            - After=2021-04-17T21:50:10.789+08:00[Asia/Shanghai]


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://121.36.142.5:7001/eureka
